name: BloodMoney CI
on:
  push:
    paths:
      - '**ci.yml'
      - '**/Config/**'
      - '**/Content/**'
      - '**/Source/**'
  pull_request:
    paths:
      - '**ci.yml'
      - '**/Config/**'
      - '**/Content/**'
      - '**/Source/**'

permissions:
  contents: read

jobs:
  windows: # Windows x64 and x86 build matrix
    permissions:
      contents: write
    strategy:
      fail-fast: false # Don't cancel other matrix jobs if one fails
      matrix:
        cfg:
        - { config: Development, os: [self-hosted, Windows, X64], platform: 'Win64', ue_path: 'C:\\Program Files\\Epic Games\\UE_5.5', target_name: 'untitledfightgame', project_path: '${{github.workspace}}\\main\\untitledfightgame.uproject' }
    name: "Windows ${{matrix.cfg.config}}"
    runs-on: ${{matrix.cfg.os}}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout Game
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: main

      - name: Clear previous exports
        run: rm exports ; mkdir exports

      - name: Build Project
        shell: pwsh
        run: '"${{matrix.cfg.ue_path}}\\Engine\\Build\\BatchFiles\\RunUAT.bat" -platform=${{matrix.cfg.platform}} -project="${{matrix.cfg.project_path}}" BuildCookRun -nop4 -utf8output -cook -target=${{matrix.cfg.target_name}} -SkipCookingEditorContent -installed -stage -archive -package -build -pak -iostore -compressed -prereqs -archivedirectory="${{github.workspace}}\\exports" -distribution -clientconfig=${{matrix.cfg.config}} -serverconfig=${{matrix.cfg.config}} -nodebuginfo -nocompile -nocompileuat'

      - name: Package distributable
        run: cd exports && Compress-Archive . winexport.zip

      - name: Upload Binary
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: "BloodMoney - Windows ${{matrix.cfg.config}}"
          path: '${{github.workspace}}\\exports\\winexport.zip'
